apiVersion: v1
kind: Service
metadata:
  name: zenith-ingestor
  labels:
    app: zenith-ingestor
spec:
  type: LoadBalancer
  selector:
    app: zenith-ingestor
  ports:
  - name: grpc-http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8082
    targetPort: 8082
    protocol: TCP
