apiVersion: v1
kind: Pod
metadata:
  name: zenith-ingestor
spec:
  containers:
    - name: zenith-ingestor
      image: zenith-ingestor:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 50051
      envFrom:
        - configMapRef:
            name: zenith-config
        - secretRef:
            name: zenith-secrets
      volumeMounts:
        - name: ca-cert
          mountPath: "/root/.postgresql"
          readOnly: true
  volumes:
    - name: ca-cert
      secret:
        secretName: zenith-ca-cert
